from .config import BOT_TOKEN, NEWS_LINK, SALES_LINK, SPARE_PARTS_LINK, EVENTS_LINK, ADDRESS_LINK, TECH_LINK, \
    WEBHOOK_URL_BASE, WEBHOOK_URL_PATH, WEBHOOK_SSL_CERT, WEBHOOK_PORT, WEBHOOK_LISTEN, WEBHOOK_SSL_PRIVATE
